

services:
  apache-web:
    build: 
      context: ./apache
      dockerfile: Dockerfile
    container_name: apache-lab
    ports:
      - "8080:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache.rule=Host(`apache.local`)"

  nginx-web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-lab
    ports:
      - "8081:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - web-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=Host(`nginx.local`)"

  # Load balancer simple avec Nginx
  load-balancer:
    image: nginx:alpine
    container_name: lb-lab
    ports:
      - "8082:80"
    volumes:
      - ./load-balancer/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - apache-web
      - nginx-web
    restart: unless-stopped
    networks:
      - web-network

networks:
  web-network:
    driver: bridge
    name: blueline-web-network
