services:
  mailserver:
    image: mailserver/docker-mailserver:latest
    hostname: mail
    domainname: example.local
    container_name: mailserver
    volumes:
      - ./mail-data/maildata:/var/mail
      - ./mail-data/config:/tmp/docker-mailserver
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - PERMIT_DOCKER=host
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    restart: unless-stopped

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    environment:
      ROUNDCUBEMAIL_DEFAULT_HOST: mailserver
      ROUNDCUBEMAIL_SMTP_SERVER: mailserver
      ROUNDCUBEMAIL_SMTP_PORT: 587
      ROUNDCUBEMAIL_IMAP_PORT: 143
    ports:
      - "8084:80"
    depends_on:
      - mailserver
    restart: unless-stopped
