services:
  bind9:
    image: internetsystemsconsortium/bind9:9.18
    container_name: bind9-lab
    ports:
      - "1053:53/tcp"
      - "1053:53/udp"
    volumes:
      - ./config:/etc/bind
      - ./zones:/var/lib/bind
    restart: unless-stopped
networks:
  default:
    name: dns-net
